# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.33
      with:
        github_token: ${{ secrets.TOKIS }}
        goos: linux
        goarch: amd64
        project_path: ./cmd